[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
env_logger = "0.11.3"
lazy_static = "1.5.0"
log = "0.4.21"
rustyline = "14.0.0"
